hotel_app/urls.py
from hotel_app.views import IndexView, HotelsView, HotelDetail, AllRooms, RoomDetail, ReservationView, CancelView
from django.urls import path
from . import views

app_name = 'hotel_app'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('hotels/', HotelsView.as_view(), name='hotel'),
    path('hotels/<int:pk>/', HotelDetail.as_view(), name='hotel_detail'),

    path('rooms/', AllRooms.as_view(), name='all_rooms'),
    path('rooms/<int:pk>/', RoomDetail.as_view(), name='room_detail'),

    path('booking/', ReservationView.as_view(), name='booking_random'),
    path('booking/<int:room_id>/', ReservationView.as_view(), name='booking'),
    path('ajax/hotel_rooms/', views.hotel_rooms, name='hotel_rooms'),

    path('cancel/<int:id>/', CancelView.as_view(), name='cancel'),
]

hotel_project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hotel_app.urls', namespace='hotel_app')),
    path('user/', include('user.urls', namespace='user'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from user.views import UserCreate, UserLogin, UserLogout, UserProfileView
app_name = 'user'

urlpatterns = [
    path('registration/', UserCreate.as_view(), name='registration'),
    path('login/', UserLogin.as_view(), name='login'),
    path('logout/', UserLogout.as_view(), name='logout'),
    path('profile/', UserProfileView.as_view(), name='profile')
]

hotel_app/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from django.db import models
from datetime import date


class Hotel(models.Model):
    hotel_image = models.ImageField(upload_to='hotel_photos', blank=True, null=True, default='hotel_def.jpg')
    hotel_star = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    hotel_contact = models.CharField(max_length=30, blank=True)
    hotel_name = models.CharField(max_length=40, unique=True)
    hotel_address = models.CharField(max_length=60)
    hotel_email = models.EmailField(blank=True)
    hotel_about = models.TextField(blank=True)

    def __str__(self):
        return self.hotel_name

    class Meta:
        verbose_name_plural = 'Hotels'
        db_table = 'Hotels'
        ordering = ['hotel_name']


class Room(models.Model):
    room_image = models.ImageField(upload_to='room_photos', blank=True, null=True, default='room_def.jpg')
    room_price = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(0)])
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE, related_name='rooms')
    room_available = models.BooleanField(default=True)
    room_type = models.CharField(max_length=30)
    room_number = models.PositiveIntegerField()

    def __str__(self):
        return f"Type - {self.room_type}, Room - {self.room_number}, Hotel - {self.hotel.hotel_name}"

    class Meta:
        db_table = 'Rooms'
        verbose_name_plural = 'Rooms'
        ordering = ['hotel', 'room_number']
        unique_together = ('hotel', 'room_number')


class RoomImages(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name='room_carusel')
    images = models.ImageField(upload_to='room_carusel')

    def __str__(self):
        return f"room {self.room.room_type}'s images"


class HotelsImages(models.Model):
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE, related_name='hotel_carusel')
    images = models.ImageField(upload_to='hotel_carusel')

    def __str__(self):
        return f"hotel {self.hotel.hotel_name}'s images"


class Reservation(models.Model):
    STATUS_CHOICE = (('active', 'active'), ('completed', 'completed'), ('canceled', 'canceled'), ('upcoming', 'upcoming'))
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE, related_name='reservations')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='reservations')
    room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name='reservations')
    guests = models.PositiveIntegerField(validators=[MinValueValidator(1), MaxValueValidator(3)])
    total_price = models.DecimalField(max_digits=10, decimal_places=2, editable=False)
    status = models.CharField(max_length=30, choices=STATUS_CHOICE, default='active')
    check_out = models.DateField()
    check_in = models.DateField()

    class Meta:
        verbose_name_plural = 'Reservations'
        db_table = 'Reservations'
        ordering = ['check_in']

    def __str__(self):
        return f"user: {self.user.username}, room: {self.room.room_type}, hotel: {self.hotel.hotel_name}, date: {self.check_in} - {self.check_out}"

    def clean(self):
        super().clean()
        if self.status == 'canceled':
            return
        if not self.room_id:
            return

        today = date.today()
        if self.check_in >= self.check_out:
            raise ValidationError({'check_out': _('Check-out must be after check-in day.')})
        elif self.check_in < today:
            raise ValidationError({'check_in': _('Check-in must be today or in the future.')})

        already_booked = Reservation.objects.filter(
            room=self.room,
            check_in__lt=self.check_out,
            check_out__gt=self.check_in,
            status__in = ['active', 'upcoming']
        ).exclude(pk=self.pk)

        if already_booked.exists():
            raise ValidationError('This room is already booked on these dates')

    def canceled(self):
        self.status = 'canceled'
        self.save()
        self.room.room_available = True
        self.room.save()

    def save(self, *args, **kwargs):
        if not self.room_id:
            return super().save(*args, **kwargs)
        self.clean()
        today = date.today()
        nights = (self.check_out - self.check_in).days
        self.total_price = nights * self.room.room_price

        if self.status != 'canceled':
            if self.check_out < today:
                self.status = 'completed'
            elif self.check_in <= today <= self.check_out:
                self.status = 'active'
            else: self.status = 'upcoming'

        super().save(*args, **kwargs)

        if self.status in ['active', 'upcoming']:
            self.room.room_available = False
        else:
            self.room.room_available = True
        self.room.save(update_fields=['room_available'])

hotel_app/forms.py
from django import forms
from django.forms import models

from hotel_app.models import Reservation, Room


class BookingForm(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = ['hotel', 'room', 'guests', 'check_in', 'check_out']
        widgets = {
            'check_in': forms.DateInput(attrs={'type': 'date'}),
            'check_out': forms.DateInput(attrs={'type': 'date'})
        }

    def __init__(self, *args, **kwargs):
        hotel_id = kwargs.pop('hotel_id',None)
        if 'data' in kwargs:
            data = kwargs['data']
            hotel_id = data.get('hotel') or data.get('hotel_id')
        super().__init__(*args, **kwargs)

        if hotel_id:
            self.fields['room'].queryset = Room.objects.filter(hotel_id=hotel_id, room_available=True)
        else:
            self.fields['room'].queryset = Room.objects.none()

hotel_app/views.py
from datetime import datetime
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView, CreateView
from django.contrib import messages
from hotel_app.forms import BookingForm
from hotel_app.models import Room, Hotel, Reservation


class IndexView(ListView):
    model = Room
    template_name = 'index.html'
    context_object_name = 'rooms'

    def get_queryset(self):
        rooms = Room.objects.all()
        search = self.request.GET.get('q')
        if search:
            rooms = rooms.filter(Q(room_type__icontains=search) | Q(hotel__hotel_name__icontains=search)).distinct()
        return rooms

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['favorite_rooms'] = Room.objects.filter(room_price__gt=200, room_available=True).order_by('-room_price')[:4]
        return context


class HotelsView(ListView):
    model = Hotel
    template_name = 'hotels.html'
    context_object_name = 'hotels'
    paginate_by = 4


class HotelDetail(DetailView):
    model = Hotel
    template_name = 'hotel_detail.html'
    context_object_name = 'hotel'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rooms'] = Room.objects.filter(hotel=self.object, room_available=True)
        context['images'] = self.object.hotel_carusel.all()
        return context


class AllRooms(ListView):
    model = Room
    template_name = 'rooms.html'
    context_object_name = 'rooms'
    paginate_by = 8

    def get_queryset(self):
        rooms = Room.objects.filter(room_available=True)
        search = self.request.GET.get('q', '').strip()
        min_price = self.request.GET.get('min_price')
        max_price = self.request.GET.get('max_price')
        room_type = self.request.GET.get('room_type')
        hotel_name = self.request.GET.get('hotel_name')
        check_in = self.request.GET.get('check_in')
        check_out = self.request.GET.get('check_out')

        if search:
            rooms = rooms.filter(Q(room_type__icontains=search) | Q(hotel__hotel_name__icontains=search)).distinct()
        if min_price:
            rooms = rooms.filter(room_price__gte=min_price)
        if max_price:
            rooms = rooms.filter(room_price__lte=max_price)
        if room_type:
            rooms = rooms.filter(room_type__icontains=room_type)
        if hotel_name:
            rooms = rooms.filter(hotel__hotel_name__icontains=hotel_name)
        if check_in and check_out:
            try:
                check_in_date = datetime.strptime(check_in, '%Y-%m-%d').date()
                check_out_date = datetime.strptime(check_out, '%Y-%m-%d').date()

                reserved_rooms = Reservation.objects.filter(
                    Q(check_in__lt=check_out_date) & Q(check_out__gt=check_in_date)
                ).values_list('room_id', flat=True)

                rooms = rooms.exclude(id__in=reserved_rooms)
            except ValueError:
                pass
        return rooms


class RoomDetail(DetailView):
    model = Room
    template_name = 'room_detail.html'
    context_object_name = 'room'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        room = self.get_object()
        context['hotel'] = room.hotel
        context['images'] = room.room_carusel.all()
        context['available'] = room.room_available
        if self.request.user.is_authenticated:
            context['user_reservations'] = room.reservations.filter(user=self.request.user)
        else:
            context['user_reservations'] = None
        return context

class ReservationView(LoginRequiredMixin, CreateView):
    model = Reservation
    form_class = BookingForm
    template_name = 'booking.html'
    success_url = reverse_lazy('user:profile')
    login_url = 'user:login'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        room_id = self.kwargs.get('room_id')
        context['hotels'] = Hotel.objects.all()

        if room_id:
            room = get_object_or_404(Room, pk=room_id)
            context['room'] = room
            context['hotel'] = room.hotel
        else:
            context['room'] = None
            context['rooms'] = Room.objects.filter(room_available=True)
            context['hotel'] = None
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        if self.request.method in ['POST', 'GET']:
            hotel_id = self.request.POST.get('hotel') or self.request.GET.get('hotel')
            if hotel_id:
                kwargs['hotel_id'] = hotel_id
        return kwargs

    def get_initial(self):
        initial = super().get_initial()
        room_id = self.kwargs.get('room_id')

        if room_id:
            room = get_object_or_404(Room, pk=room_id)
            initial['room'] = room
            initial['hotel'] = room.hotel
        return initial

    def form_valid(self, form):
        form.instance.user = self.request.user
        room_id = self.kwargs.get('room_id')

        if room_id:
            room = get_object_or_404(Room, pk=room_id)
        else:
            room = form.cleaned_data.get('room')

        if not room:
            form.add_error('room', 'Please select a room.')
            return self.form_invalid(form)

        if not room.room_available:
            form.add_error('room', 'This room is already booked.')
            return self.form_invalid(form)

        form.instance.room = room
        form.instance.hotel = room.hotel

        return super().form_valid(form)

def hotel_rooms(request):
    hotel_id = request.GET.get('hotel_id')
    rooms = Room.objects.filter(hotel_id=hotel_id, room_available=True)
    html = '<option value="">---------</option>'
    for room in rooms:
        html += f'<option value="{room.id}">Room Type: {room.room_type} - Room Number: {room.room_number}</option>'
    return HttpResponse(html)


class CancelView(LoginRequiredMixin, View):
    def post(self, request, id):
        reservation = get_object_or_404(Reservation, pk=id, user=request.user)

        if reservation.status != 'canceled':
            reservation.canceled()
            messages.success(request, 'Reservation successfully canceled!')
        else:
            messages.warning(request, 'This reservation is already canceled!')

        return redirect('user:profile')

hotel_app/templates/booking.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-6">
                <form method="post">
                    {% csrf_token %}
                    {{ form.non_field_errors }}
                    {% if room %}
                    <h2 class="text-center">Book Room: <span class="or_color">{{ room.room_type }}</span> Of Hotel <span class="or_color">{{ room.hotel.hotel_name }}</span></h2>
                        <input type="hidden" name="room" value="{{ room.id }}">
                        <input type="hidden" name="hotel" value="{{ hotel.id }}">

                        <div class="form-group">
                            <label for="hotel_label">Hotel:</label>
                            <input type="text" class="form-control" id="hotel_label" value="{{ room.hotel.hotel_name }}" readonly>
                        </div>
                        <div class="form-group">
                            <label for="room_label">Room:</label>
                            <input type="text" id="room_label" class="form-control" value="{{ room.room_type }}" readonly>
                        </div>

                        <div class="checkin_box">
                        {{ form.check_in|as_crispy_field }}
                        {{ form.check_out|as_crispy_field }}
                        {{ form.guests|as_crispy_field }}
                    </div>
                    {% else %}
                    <h2 class="or_color text-center">Book Room</h2>
                        {{ form|crispy }}
                    {% endif %}
                    <div class="d-flex justify-content-center ">
                        <button type="submit" class="btn btn-success mt-3">Booking</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function() {
            $('#id_hotel').change(function() {
                var hotelId = $(this).val();
                $.ajax({
                    url: "{% url 'hotel_app:hotel_rooms' %}",
                    data: {'hotel_id': hotelId},
                    success: function(data) {
                        $('#id_room').html(data);
                    }
                });
            });
        });
    </script>
{% endblock %}

hotel_app/templates/hotel_detail.html
{% extends 'base.html' %}
{% block title %} main page {% endblock %}
{% block body %}
    <div class="container mt-3">
        <div class="row mb-5 border-bottom border-dark pb-5">
            <div class="col-8">
                <img src="{{ hotel.hotel_image.url }}" class="hotel_image w-100 h-100" alt="courtyard marriott">
            </div>
            <div class="col-4 text-center align-content-center">
                <h1 class="or_color"> {{ hotel.hotel_name }}</h1>
                <p>Address: {{ hotel.hotel_address }}</p>
                <p>Star: {{ hotel.hotel_star }}</p>
                <p>Contact: {{ hotel.hotel_contact }}</p>
                <p>Email: {{ hotel.hotel_email }}</p>
            </div>
        </div>
        <div class="row">
            <div id="roomCarousel" class="carousel slide" data-bs-ride="carousel">
                <div id="carouselExampleFade" class="carousel slide carousel-fade mx-auto w-75" data-bs-ride="carousel" style="height: 400px;">
                    <div class="carousel-indicators">
                        {% for image in images %}
                            <button type="button" data-bs-target="#carouselExampleFade" data-bs-slide-to="{{ forloop.counter0 }}" class="{% if forloop.first %}active{% endif %}"
                                    aria-current="{% if forloop.first %}true{% endif %}" aria-label="Slide {{ forloop.counter }}">
                            </button>
                        {% endfor %}
                    </div>
                    <div class="carousel-inner h-100">
                        {% for image in images %}
                            <div class="carousel-item {% if forloop.first %}active{% endif %} h-100">
                                <img src="{{ image.images.url }}" class="d-block w-100 h-100" style="object-fit: cover;" alt="Hotel Image">
                            </div>
                        {% endfor %}
                    </div>
                    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Next</span>
                    </button>
                </div>
            </div>
        </div>
        <div class="row text-center mt-5">
            <h2 class="or_color">About {{ hotel.hotel_name }}</h2>
            <hr>
            <p>About: {{ hotel.hotel_about }}</p>
        </div>
    </div>
    <div class="container border-top border-dark">
       <div class="row justify-content-center g-4">
           <h2 class="text-center mb-5 mt-5 main_title or_color">Hotel Rooms</h2>
           {% for room in rooms %}
               <div class="col-3">
                   <div class="card border-dark" style="width: 18rem;">
                       <img src="{{ room.room_image.url }}" class="card-img-top" alt="...">
                       <div class="card-body">
                           <h5 class="card-title">Room Type: {{ room.room_type }}</h5>
                           <p class="card-text">Price: {{ room.room_price }}$</p>
                           <p class="card-text">Room Number: {{ room.room_number }}</p>
                           <div class="d-flex justify-content-between">
                               <a href="{% url 'hotel_app:room_detail' pk=room.pk %}" class="btn btn-primary">See Room</a>
                               <a href="{% url 'hotel_app:booking' room_id=room.pk %}" class="btn btn-success">Book Room</a>
                           </div>
                       </div>
                   </div>
               </div>
           {% endfor %}
       </div>
    </div>
{% endblock %}

hotel_app/templates/hotels.html
{% extends 'base.html' %}
{% block title %} Hotels {% endblock %}
{% block body %}
    <div class="container">
        <div class="row justify-content-center g-4">
            <h1 class="text-center mb-5 mt-5 main_title or_color">All Hotels</h1>
            {% for hotel in hotels %}
                <div class="col-3">
                    <div class="card border-dark" style="width: 18rem;">
                        <img src="{{ hotel.hotel_image.url }}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">Hotel: {{ hotel.hotel_name }}</h5>
                            <p class="card-text">Star: {{ hotel.hotel_star }}</p>
                            <p class="card-text">Address: {{ hotel.hotel_address }}</p>
                            <a href="{% url 'hotel_app:hotel_detail' pk=hotel.pk %}" class="btn btn-primary">See Hotel Detail</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

hotel_app/templates/index.html
{% extends 'base.html' %}
{% block title %} main page {% endblock %}
{% block body %}
    <div class="container">
        <div class="row">
            <div class="main_photo">
                <h1 class="text-white fw-bold p-5 logo_title">Five-Star Hotels</h1>
            </div>
        </div>
    </div>
    <div class="container mb-5">
        <div class="row justify-content-center g-4">
            <h1 class="text-center mb-5 mt-5 main_title or_color">Favorite Rooms</h1>
            {% for room in favorite_rooms %}
                <div class="col-3">
                    <div class="card border-dark" style="width: 18rem;">
                        <img src="{{ room.room_image.url }}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title">Room Type: {{ room.room_type }}</h5>
                            <p class="card-text">Hotel: {{ room.hotel.hotel_name }}</p>
                            <p class="card-text">Price: {{ room.room_price }}$</p>
                            <p class="card-text">Room Number: {{ room.room_number }}</p>
                            <div class="d-flex justify-content-between">
                                <a href="{% url 'hotel_app:room_detail' pk=room.pk %}" class="btn btn-primary">See Room</a>
                                <a href="{% url 'hotel_app:booking' room_id=room.pk %}" class="btn btn-success">book room</a>
                            </div>
                        </div>
                    </div>
               </div>
           {% endfor %}
        </div>
    </div>
{% endblock %}

hotel_app/templates/room_detail.html
{% extends 'base.html' %}
{% block title %} main page {% endblock %}
{% block body %}
    <div class="container mt-5">
        <h2 class="text-center mb-4 or_color"> - Room {{ room.room_type }} - Of {{ room.hotel.hotel_name }}</h2>
        <div id="roomCarousel" class="carousel slide" data-bs-ride="carousel">
            <div id="carouselExampleFade" class="carousel slide carousel-fade mx-auto w-75" data-bs-ride="carousel" style="height: 400px;">
                <div class="carousel-indicators">
                    {% for image in images %}
                        <button type="button" data-bs-target="#carouselExampleFade" data-bs-slide-to="{{ forloop.counter0 }}" class="{% if forloop.first %}active{% endif %}"
                                aria-current="{% if forloop.first %}true{% endif %}" aria-label="Slide {{ forloop.counter }}">
                        </button>
                    {% endfor %}
                </div>
                <div class="carousel-inner h-100">
                    {% for image in images %}
                        <div class="carousel-item {% if forloop.first %}active{% endif %} h-100">
                            <img src="{{ image.images.url }}" class="d-block w-100 h-100" style="object-fit: cover;" alt="Room Image">
                        </div>
                    {% endfor %}
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </button>
            </div>

            <div class="mt-4 d-flex justify-content-center gap-4">
                <p class="fs-5"><span class="or_color"> Room Number:</span> {{ room.room_number }}</p>
                <p class="fs-5"><span class="or_color"> Price:</span> {{ room.room_price }}$</p>
                <p class="fs-5"><span class="or_color"> Availability:</span> {{ room.room_available|yesno:"Available,Not Available" }}</p>
            </div>
            <div class="d-flex justify-content-center ">
                <a href="{% url 'hotel_app:booking' room_id=room.pk %}" class="btn btn-success fs-5 mb-5 mt-3">Book this room</a>
            </div>
        </div>
    </div>
{% endblock %}

hotel_app/templates/rooms.html
{% extends 'base.html' %}
{% block title %} All Rooms {% endblock %}
{% block body %}
   <div class="container">
       <div class="row">
           <div class="col-12 mt-3 align-items-center border-bottom border-top rounded-4 border-dark  p-3">
               <form action="{% url 'hotel_app:all_rooms' %}" class="d-flex gap-2">
                   <input type="number" class="form-control border-dark" name="min_price" placeholder="min. price" value="{{ request.GET.min_price }}">
                   <input type="number" class="form-control border-dark" name="max_price" placeholder="max. price" value="{{ request.GET.max_price }}">
                   <input type="text" class="form-control border-dark" name="room_type" placeholder="room type" value="{{ request.GET.room_type }}">
                   <input type="text" class="form-control border-dark" name="hotel_name" placeholder="hotel name" value="{{ request.GET.hotel_name }}">
                   <input type="date" class="form-control border-dark" name="check_in" placeholder="check-in" value="{{ request.GET.check_in }}">
                   <input type="date" class="form-control border-dark" name="check_out" placeholder="check-out" value="{{ request.GET.check_out }}">
                   <button type="submit" class="btn btn-warning ">Filter</button>
               </form>
           </div>
       </div>
       <div class="row justify-content-center g-4">
           <h1 class="text-center mb-5 mt-5 main_title or_color">All Rooms</h1>
           {% for room in rooms %}
               <div class="col-3 mt-3">
                   <div class="card border-dark" style="width: 18rem;">
                       <img src="{{ room.room_image.url }}" class="card-img-top" alt="...">
                       <div class="card-body">
                           <h5 class="card-title">Room Type: {{ room.room_type }}</h5>
                           <p class="card-title">Hotel: {{ room.hotel.hotel_name }}</p>
                           <p class="card-title">Room Number: {{ room.room_number }}</p>
                           <p class="card-title">Room Price: {{ room.room_price }}$</p>
                           <div class="d-flex justify-content-between pt-2">
                               <a href="{% url 'hotel_app:room_detail' pk=room.pk %}" class="btn btn-primary">See Room</a>
                               <a href="{% url 'hotel_app:booking' room_id=room.pk %}" class="btn btn-success">Book Room</a>
                           </div>
                       </div>
                   </div>
               </div>
           {% endfor %}
       </div>
   </div>
{% endblock %}