hotel_app/urls.py
from hotel_app.views import IndexView, HotelsView, HotelDetail, AllRooms, RoomDetail, ReservationView, CancelView
from django.urls import path
from . import views

app_name = 'hotel_app'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('hotels/', HotelsView.as_view(), name='hotel'),
    path('hotels/<int:pk>/', HotelDetail.as_view(), name='hotel_detail'),

    path('rooms/', AllRooms.as_view(), name='all_rooms'),
    path('rooms/<int:pk>/', RoomDetail.as_view(), name='room_detail'),

    path('booking/', ReservationView.as_view(), name='booking_random'),
    path('booking/<int:room_id>/', ReservationView.as_view(), name='booking'),
    path('ajax/hotel_rooms/', views.hotel_rooms, name='hotel_rooms'),

    path('cancel/<int:id>/', CancelView.as_view(), name='cancel'),
]

hotel_project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hotel_app.urls', namespace='hotel_app')),
    path('user/', include('user.urls', namespace='user'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from user.views import UserCreate, UserLogin, UserLogout, UserProfileView
app_name = 'user'

urlpatterns = [
    path('registration/', UserCreate.as_view(), name='registration'),
    path('login/', UserLogin.as_view(), name='login'),
    path('logout/', UserLogout.as_view(), name='logout'),
    path('profile/', UserProfileView.as_view(), name='profile')
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <div class="container-fluid ps-5 pe-5">
        <nav class="navbar nav_main navbar-expand-lg navbar-custom border">
            <div class="container-fluid pe-3 ps-3">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 border-end border-dark border-3">
                        <li class="nav-item ">
                            <a class="nav-link nav_li me-3 rounded-2  nav_page text-dark fs-6 " href="{% url 'hotel_app:index' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link nav_li me-3 rounded-2  text-dark fs-6 " href="{% url 'hotel_app:hotel' %}">Hotels</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link nav_li me-4 rounded-2  text-dark fs-6 " href="{% url 'hotel_app:all_rooms' %}">Rooms</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link nav_li me-5 rounded-2  text-dark fs-6 " href="{% url 'hotel_app:booking_random' %}">Book Room</a>
                        </li>
                    </ul>
                    <form class="d-flex me-5 pe-3 ps-3 border-start border-end border-dark border-3" role="search" action="{% url 'hotel_app:all_rooms' %}">
                        <input class="form-control me-2" type="search" placeholder="Room type or hotel" aria-label="Search" name="q" value="{{ request.GET.q }}"/>
                        <button class="btn btn-primary" type="submit">Search</button>
                    </form>
                    <div class="d-flex justify-content-end border border-dark rounded-3 p-2">
                        {% if user.is_authenticated %}
                            <a class="btn btn-success rounded-2 text-white me-2" href="{% url 'user:profile' %}">{{ user }}</a>
                            <form action="{% url 'user:logout' %}" method="POST">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger text-white">Logout</button>
                            </form>
                        {% else %}
                            <a class="btn btn-primary border border-secondary rounded-2 text-white me-2" href="{% url 'user:login' %}">Login</a>
                            <a class="btn btn-success border border-secondary rounded-2 text-white" href="{% url 'user:registration' %}">Register</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
        {% block body %}

        {% endblock %}
    </div>
        {% if is_paginated %}
            <nav aria-label="Page navigation example" class="mt-5 mb-5">
                <ul class="pagination justify-content-center">
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#" tabindex="-1">Previous</a>
                        </li>
                    {% endif %}

                    {% for num in paginator.page_range %}
                        {% if num == page_obj.number %}
                            <li class="page-item active">
                                <a class="page-link" href="#">{{ num }}</a>
                            </li>
                        {% else %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}

                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" href="#">Next</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        {% endif %}
        {% block footer %}
            <div class="container-fluid mt-5 footer">
                <h3 class="text-center p-5">There is All Information About Our Site</h3>
                <h3 class="text-center pb-5">About Administrator</h3>
            </div>
        {% endblock %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
</body>
</html>